// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comunicacion.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Jugada struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Jugada               int32    `protobuf:"varint,2,opt,name=Jugada,proto3" json:"Jugada,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Jugada) Reset()         { *m = Jugada{} }
func (m *Jugada) String() string { return proto.CompactTextString(m) }
func (*Jugada) ProtoMessage()    {}
func (*Jugada) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{2}
}

func (m *Jugada) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jugada.Unmarshal(m, b)
}
func (m *Jugada) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jugada.Marshal(b, m, deterministic)
}
func (m *Jugada) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jugada.Merge(m, src)
}
func (m *Jugada) XXX_Size() int {
	return xxx_messageInfo_Jugada.Size(m)
}
func (m *Jugada) XXX_DiscardUnknown() {
	xxx_messageInfo_Jugada.DiscardUnknown(m)
}

var xxx_messageInfo_Jugada proto.InternalMessageInfo

func (m *Jugada) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Jugada) GetJugada() int32 {
	if m != nil {
		return m.Jugada
	}
	return 0
}

type Resultado struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Estado               int32    `protobuf:"varint,2,opt,name=Estado,proto3" json:"Estado,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resultado) Reset()         { *m = Resultado{} }
func (m *Resultado) String() string { return proto.CompactTextString(m) }
func (*Resultado) ProtoMessage()    {}
func (*Resultado) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{3}
}

func (m *Resultado) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resultado.Unmarshal(m, b)
}
func (m *Resultado) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resultado.Marshal(b, m, deterministic)
}
func (m *Resultado) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resultado.Merge(m, src)
}
func (m *Resultado) XXX_Size() int {
	return xxx_messageInfo_Resultado.Size(m)
}
func (m *Resultado) XXX_DiscardUnknown() {
	xxx_messageInfo_Resultado.DiscardUnknown(m)
}

var xxx_messageInfo_Resultado proto.InternalMessageInfo

func (m *Resultado) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Resultado) GetEstado() int32 {
	if m != nil {
		return m.Estado
	}
	return 0
}

type Jugada2 struct {
	ID1                  []int32  `protobuf:"varint,1,rep,packed,name=ID1,proto3" json:"ID1,omitempty"`
	ID2                  []int32  `protobuf:"varint,2,rep,packed,name=ID2,proto3" json:"ID2,omitempty"`
	Jugada1              []int32  `protobuf:"varint,3,rep,packed,name=Jugada1,proto3" json:"Jugada1,omitempty"`
	Jugada2              []int32  `protobuf:"varint,4,rep,packed,name=Jugada2,proto3" json:"Jugada2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Jugada2) Reset()         { *m = Jugada2{} }
func (m *Jugada2) String() string { return proto.CompactTextString(m) }
func (*Jugada2) ProtoMessage()    {}
func (*Jugada2) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{4}
}

func (m *Jugada2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jugada2.Unmarshal(m, b)
}
func (m *Jugada2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jugada2.Marshal(b, m, deterministic)
}
func (m *Jugada2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jugada2.Merge(m, src)
}
func (m *Jugada2) XXX_Size() int {
	return xxx_messageInfo_Jugada2.Size(m)
}
func (m *Jugada2) XXX_DiscardUnknown() {
	xxx_messageInfo_Jugada2.DiscardUnknown(m)
}

var xxx_messageInfo_Jugada2 proto.InternalMessageInfo

func (m *Jugada2) GetID1() []int32 {
	if m != nil {
		return m.ID1
	}
	return nil
}

func (m *Jugada2) GetID2() []int32 {
	if m != nil {
		return m.ID2
	}
	return nil
}

func (m *Jugada2) GetJugada1() []int32 {
	if m != nil {
		return m.Jugada1
	}
	return nil
}

func (m *Jugada2) GetJugada2() []int32 {
	if m != nil {
		return m.Jugada2
	}
	return nil
}

type Jugada3 struct {
	ID1                  int32    `protobuf:"varint,1,opt,name=ID1,proto3" json:"ID1,omitempty"`
	ID2                  int32    `protobuf:"varint,2,opt,name=ID2,proto3" json:"ID2,omitempty"`
	Jugada1              int32    `protobuf:"varint,3,opt,name=Jugada1,proto3" json:"Jugada1,omitempty"`
	Jugada2              int32    `protobuf:"varint,4,opt,name=Jugada2,proto3" json:"Jugada2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Jugada3) Reset()         { *m = Jugada3{} }
func (m *Jugada3) String() string { return proto.CompactTextString(m) }
func (*Jugada3) ProtoMessage()    {}
func (*Jugada3) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{5}
}

func (m *Jugada3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jugada3.Unmarshal(m, b)
}
func (m *Jugada3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jugada3.Marshal(b, m, deterministic)
}
func (m *Jugada3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jugada3.Merge(m, src)
}
func (m *Jugada3) XXX_Size() int {
	return xxx_messageInfo_Jugada3.Size(m)
}
func (m *Jugada3) XXX_DiscardUnknown() {
	xxx_messageInfo_Jugada3.DiscardUnknown(m)
}

var xxx_messageInfo_Jugada3 proto.InternalMessageInfo

func (m *Jugada3) GetID1() int32 {
	if m != nil {
		return m.ID1
	}
	return 0
}

func (m *Jugada3) GetID2() int32 {
	if m != nil {
		return m.ID2
	}
	return 0
}

func (m *Jugada3) GetJugada1() int32 {
	if m != nil {
		return m.Jugada1
	}
	return 0
}

func (m *Jugada3) GetJugada2() int32 {
	if m != nil {
		return m.Jugada2
	}
	return 0
}

type RequestJugadas struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestJugadas) Reset()         { *m = RequestJugadas{} }
func (m *RequestJugadas) String() string { return proto.CompactTextString(m) }
func (*RequestJugadas) ProtoMessage()    {}
func (*RequestJugadas) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{6}
}

func (m *RequestJugadas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestJugadas.Unmarshal(m, b)
}
func (m *RequestJugadas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestJugadas.Marshal(b, m, deterministic)
}
func (m *RequestJugadas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestJugadas.Merge(m, src)
}
func (m *RequestJugadas) XXX_Size() int {
	return xxx_messageInfo_RequestJugadas.Size(m)
}
func (m *RequestJugadas) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestJugadas.DiscardUnknown(m)
}

var xxx_messageInfo_RequestJugadas proto.InternalMessageInfo

func (m *RequestJugadas) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type RequestPozoActual struct {
	Pozo                 int32    `protobuf:"varint,1,opt,name=Pozo,proto3" json:"Pozo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestPozoActual) Reset()         { *m = RequestPozoActual{} }
func (m *RequestPozoActual) String() string { return proto.CompactTextString(m) }
func (*RequestPozoActual) ProtoMessage()    {}
func (*RequestPozoActual) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{7}
}

func (m *RequestPozoActual) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPozoActual.Unmarshal(m, b)
}
func (m *RequestPozoActual) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPozoActual.Marshal(b, m, deterministic)
}
func (m *RequestPozoActual) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPozoActual.Merge(m, src)
}
func (m *RequestPozoActual) XXX_Size() int {
	return xxx_messageInfo_RequestPozoActual.Size(m)
}
func (m *RequestPozoActual) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPozoActual.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPozoActual proto.InternalMessageInfo

func (m *RequestPozoActual) GetPozo() int32 {
	if m != nil {
		return m.Pozo
	}
	return 0
}

type ResponsePozoActual struct {
	Pozo                 int32    `protobuf:"varint,1,opt,name=Pozo,proto3" json:"Pozo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponsePozoActual) Reset()         { *m = ResponsePozoActual{} }
func (m *ResponsePozoActual) String() string { return proto.CompactTextString(m) }
func (*ResponsePozoActual) ProtoMessage()    {}
func (*ResponsePozoActual) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e958f10881bcae0, []int{8}
}

func (m *ResponsePozoActual) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponsePozoActual.Unmarshal(m, b)
}
func (m *ResponsePozoActual) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponsePozoActual.Marshal(b, m, deterministic)
}
func (m *ResponsePozoActual) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponsePozoActual.Merge(m, src)
}
func (m *ResponsePozoActual) XXX_Size() int {
	return xxx_messageInfo_ResponsePozoActual.Size(m)
}
func (m *ResponsePozoActual) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponsePozoActual.DiscardUnknown(m)
}

var xxx_messageInfo_ResponsePozoActual proto.InternalMessageInfo

func (m *ResponsePozoActual) GetPozo() int32 {
	if m != nil {
		return m.Pozo
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "grpc.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "grpc.HelloReply")
	proto.RegisterType((*Jugada)(nil), "grpc.Jugada")
	proto.RegisterType((*Resultado)(nil), "grpc.Resultado")
	proto.RegisterType((*Jugada2)(nil), "grpc.Jugada2")
	proto.RegisterType((*Jugada3)(nil), "grpc.Jugada3")
	proto.RegisterType((*RequestJugadas)(nil), "grpc.RequestJugadas")
	proto.RegisterType((*RequestPozoActual)(nil), "grpc.RequestPozoActual")
	proto.RegisterType((*ResponsePozoActual)(nil), "grpc.ResponsePozoActual")
}

func init() { proto.RegisterFile("comunicacion.proto", fileDescriptor_5e958f10881bcae0) }

var fileDescriptor_5e958f10881bcae0 = []byte{
	// 467 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x65, 0x27, 0x6d, 0xe9, 0x24, 0xb4, 0x65, 0x85, 0xc0, 0xca, 0x29, 0xf2, 0x01, 0x22,
	0x41, 0xed, 0x76, 0xcd, 0x03, 0x50, 0x14, 0x04, 0x41, 0x6d, 0x41, 0xce, 0x8d, 0xdb, 0xda, 0x1e,
	0x05, 0x0b, 0xc7, 0x6b, 0xbc, 0x5e, 0xa4, 0xf2, 0x0e, 0x3c, 0x1e, 0xef, 0x83, 0xd6, 0xde, 0x6d,
	0x1c, 0xb6, 0xa4, 0x12, 0x9c, 0xb2, 0xf3, 0xcf, 0x37, 0x9a, 0xdf, 0x33, 0xa3, 0x00, 0x49, 0xf9,
	0x5a, 0x96, 0x79, 0xca, 0xd2, 0x9c, 0x97, 0x41, 0x55, 0xf3, 0x86, 0x93, 0xe1, 0xaa, 0xae, 0x52,
	0xdf, 0x87, 0xf1, 0x7b, 0x2c, 0x0a, 0x1e, 0xe3, 0x37, 0x89, 0xa2, 0x21, 0x04, 0x86, 0xd7, 0x6c,
	0x8d, 0x9e, 0x33, 0x75, 0x66, 0x87, 0x71, 0xfb, 0xf6, 0x9f, 0x01, 0x68, 0xa6, 0x2a, 0x6e, 0x88,
	0x07, 0x07, 0x57, 0x28, 0x04, 0x5b, 0x19, 0xc8, 0x84, 0xfe, 0x19, 0xec, 0x7f, 0x90, 0x2b, 0x96,
	0x31, 0x72, 0x04, 0xee, 0x62, 0xde, 0xa6, 0xf7, 0x62, 0x77, 0x31, 0x27, 0x4f, 0x4c, 0xc6, 0x73,
	0x5b, 0x4d, 0x47, 0x7e, 0x04, 0x87, 0x31, 0x0a, 0x59, 0x34, 0x2c, 0xe3, 0x77, 0x15, 0xbd, 0x15,
	0x2a, 0x63, 0x8a, 0xba, 0xc8, 0x67, 0x70, 0xd0, 0x95, 0x53, 0x72, 0x02, 0x83, 0xc5, 0xfc, 0xdc,
	0x73, 0xa6, 0x83, 0xd9, 0x5e, 0xac, 0x9e, 0x9d, 0x42, 0x3d, 0xd7, 0x28, 0x54, 0xf9, 0xed, 0xf0,
	0x73, 0x6f, 0xd0, 0xaa, 0x26, 0xdc, 0x64, 0xa8, 0x37, 0xec, 0x67, 0xe8, 0xa6, 0x45, 0xb4, 0x69,
	0xe1, 0x58, 0x2d, 0x9c, 0x3b, 0x5b, 0x38, 0x7f, 0x6d, 0xe1, 0xf4, 0x5b, 0x4c, 0xe1, 0x48, 0xcf,
	0xbc, 0x53, 0xc4, 0x9f, 0xdf, 0xef, 0x3f, 0x87, 0x47, 0x9a, 0xf8, 0xc4, 0x7f, 0xf0, 0x8b, 0xb4,
	0x91, 0xac, 0x50, 0xfb, 0x51, 0x91, 0xc6, 0xda, 0xb7, 0x3f, 0x03, 0x12, 0xa3, 0xa8, 0x78, 0x29,
	0x70, 0x37, 0x49, 0x7f, 0xba, 0x30, 0xbe, 0xcc, 0x33, 0xac, 0x97, 0x58, 0x7f, 0xcf, 0x53, 0x24,
	0x67, 0xf0, 0x60, 0xc9, 0x6e, 0xda, 0xed, 0x12, 0x12, 0xa8, 0x8b, 0x08, 0xfa, 0xe7, 0x30, 0x39,
	0xd9, 0xd2, 0xd4, 0xfa, 0x5f, 0xc3, 0xa8, 0xe7, 0x8a, 0x3c, 0xed, 0x00, 0xcb, 0xe8, 0xc4, 0x33,
	0x09, 0xcb, 0xd8, 0x0b, 0x80, 0x25, 0x96, 0x99, 0x3e, 0x95, 0x71, 0xc7, 0x75, 0xd1, 0xe4, 0xf8,
	0xb6, 0x4a, 0x1f, 0xc5, 0x29, 0x8c, 0x36, 0x30, 0x25, 0x0f, 0xfb, 0x34, 0xbd, 0x07, 0x8f, 0xb6,
	0xf1, 0xc8, 0xc2, 0xe9, 0x2f, 0x07, 0x8e, 0xd5, 0x89, 0x5f, 0xf3, 0x0c, 0xcd, 0x48, 0x5e, 0xee,
	0xb0, 0x67, 0x8f, 0x23, 0xd8, 0xe9, 0xef, 0x1e, 0xde, 0x32, 0x68, 0xf3, 0xaf, 0x00, 0xde, 0xe1,
	0xed, 0x89, 0x3c, 0xde, 0x9a, 0xb6, 0x56, 0xed, 0x2a, 0xfa, 0x11, 0x46, 0x6a, 0xe0, 0xe6, 0x93,
	0xfe, 0x7b, 0x67, 0x6f, 0xd6, 0x9f, 0xbf, 0xae, 0xf2, 0xe6, 0x8b, 0x4c, 0x82, 0x94, 0xaf, 0xc3,
	0xab, 0xfa, 0xa2, 0x64, 0x69, 0x81, 0x8d, 0x14, 0xe1, 0x25, 0x4b, 0xe8, 0xe9, 0x3c, 0x17, 0x4d,
	0x9d, 0x27, 0x32, 0xcf, 0xb8, 0x08, 0xab, 0x5a, 0x62, 0xc2, 0xc2, 0xf6, 0x5f, 0x26, 0xfc, 0xa7,
	0xaa, 0x64, 0xbf, 0xfd, 0x89, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x40, 0xac, 0x87, 0xe6, 0xb8,
	0x04, 0x00, 0x00,
}
