// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BrokerServiceClient is the client API for BrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerServiceClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	EnviarComando(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type brokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerServiceClient(cc grpc.ClientConnInterface) BrokerServiceClient {
	return &brokerServiceClient{cc}
}

func (c *brokerServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/grpc.BrokerService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *brokerServiceClient) EnviarComando(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/grpc.BrokerService/EnviarComando", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServiceServer is the server API for BrokerService service.
// All implementations must embed UnimplementedBrokerServiceServer
// for forward compatibility
type BrokerServiceServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	EnviarComando(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedBrokerServiceServer()
}

// UnimplementedBrokerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerServiceServer struct {
}

func (UnimplementedBrokerServiceServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedBrokerServiceServer) EnviarComando(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarComando not implemented")
}
func (UnimplementedBrokerServiceServer) mustEmbedUnimplementedBrokerServiceServer() {}

// UnsafeBrokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServiceServer will
// result in compilation errors.
type UnsafeBrokerServiceServer interface {
	mustEmbedUnimplementedBrokerServiceServer()
}

func RegisterBrokerServiceServer(s grpc.ServiceRegistrar, srv BrokerServiceServer) {
	s.RegisterService(&BrokerService_ServiceDesc, srv)
}

func _BrokerService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BrokerService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BrokerService_EnviarComando_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).EnviarComando(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.BrokerService/EnviarComando",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).EnviarComando(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerService_ServiceDesc is the grpc.ServiceDesc for BrokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.BrokerService",
	HandlerType: (*BrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _BrokerService_SayHello_Handler,
		},
		{
			MethodName: "EnviarComando",
			Handler:    _BrokerService_EnviarComando_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/comunicacion.proto",
}

// FulcrumServiceClient is the client API for FulcrumService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FulcrumServiceClient interface {
	EnviarComando(ctx context.Context, in *ComandoSend, opts ...grpc.CallOption) (*ComandoReply, error)
	EnviarComandoLeia(ctx context.Context, in *ComandoSend, opts ...grpc.CallOption) (*Rebeldes, error)
	InformarMerge(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	InformarInicioEnvio(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	EnviarComandoMerge(ctx context.Context, in *ComandoSend, opts ...grpc.CallOption) (*ComandoReply, error)
	Mergan(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	EnviarComandoMergeFinal(ctx context.Context, in *ComandoSend, opts ...grpc.CallOption) (*ComandoReply, error)
}

type fulcrumServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFulcrumServiceClient(cc grpc.ClientConnInterface) FulcrumServiceClient {
	return &fulcrumServiceClient{cc}
}

func (c *fulcrumServiceClient) EnviarComando(ctx context.Context, in *ComandoSend, opts ...grpc.CallOption) (*ComandoReply, error) {
	out := new(ComandoReply)
	err := c.cc.Invoke(ctx, "/grpc.FulcrumService/EnviarComando", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulcrumServiceClient) EnviarComandoLeia(ctx context.Context, in *ComandoSend, opts ...grpc.CallOption) (*Rebeldes, error) {
	out := new(Rebeldes)
	err := c.cc.Invoke(ctx, "/grpc.FulcrumService/EnviarComandoLeia", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulcrumServiceClient) InformarMerge(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/grpc.FulcrumService/InformarMerge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulcrumServiceClient) InformarInicioEnvio(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/grpc.FulcrumService/InformarInicioEnvio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulcrumServiceClient) EnviarComandoMerge(ctx context.Context, in *ComandoSend, opts ...grpc.CallOption) (*ComandoReply, error) {
	out := new(ComandoReply)
	err := c.cc.Invoke(ctx, "/grpc.FulcrumService/EnviarComandoMerge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulcrumServiceClient) Mergan(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/grpc.FulcrumService/Mergan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fulcrumServiceClient) EnviarComandoMergeFinal(ctx context.Context, in *ComandoSend, opts ...grpc.CallOption) (*ComandoReply, error) {
	out := new(ComandoReply)
	err := c.cc.Invoke(ctx, "/grpc.FulcrumService/EnviarComandoMergeFinal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FulcrumServiceServer is the server API for FulcrumService service.
// All implementations must embed UnimplementedFulcrumServiceServer
// for forward compatibility
type FulcrumServiceServer interface {
	EnviarComando(context.Context, *ComandoSend) (*ComandoReply, error)
	EnviarComandoLeia(context.Context, *ComandoSend) (*Rebeldes, error)
	InformarMerge(context.Context, *HelloRequest) (*HelloReply, error)
	InformarInicioEnvio(context.Context, *HelloRequest) (*HelloReply, error)
	EnviarComandoMerge(context.Context, *ComandoSend) (*ComandoReply, error)
	Mergan(context.Context, *HelloRequest) (*HelloReply, error)
	EnviarComandoMergeFinal(context.Context, *ComandoSend) (*ComandoReply, error)
	mustEmbedUnimplementedFulcrumServiceServer()
}

// UnimplementedFulcrumServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFulcrumServiceServer struct {
}

func (UnimplementedFulcrumServiceServer) EnviarComando(context.Context, *ComandoSend) (*ComandoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarComando not implemented")
}
func (UnimplementedFulcrumServiceServer) EnviarComandoLeia(context.Context, *ComandoSend) (*Rebeldes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarComandoLeia not implemented")
}
func (UnimplementedFulcrumServiceServer) InformarMerge(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InformarMerge not implemented")
}
func (UnimplementedFulcrumServiceServer) InformarInicioEnvio(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InformarInicioEnvio not implemented")
}
func (UnimplementedFulcrumServiceServer) EnviarComandoMerge(context.Context, *ComandoSend) (*ComandoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarComandoMerge not implemented")
}
func (UnimplementedFulcrumServiceServer) Mergan(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mergan not implemented")
}
func (UnimplementedFulcrumServiceServer) EnviarComandoMergeFinal(context.Context, *ComandoSend) (*ComandoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnviarComandoMergeFinal not implemented")
}
func (UnimplementedFulcrumServiceServer) mustEmbedUnimplementedFulcrumServiceServer() {}

// UnsafeFulcrumServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FulcrumServiceServer will
// result in compilation errors.
type UnsafeFulcrumServiceServer interface {
	mustEmbedUnimplementedFulcrumServiceServer()
}

func RegisterFulcrumServiceServer(s grpc.ServiceRegistrar, srv FulcrumServiceServer) {
	s.RegisterService(&FulcrumService_ServiceDesc, srv)
}

func _FulcrumService_EnviarComando_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComandoSend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulcrumServiceServer).EnviarComando(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FulcrumService/EnviarComando",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulcrumServiceServer).EnviarComando(ctx, req.(*ComandoSend))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulcrumService_EnviarComandoLeia_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComandoSend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulcrumServiceServer).EnviarComandoLeia(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FulcrumService/EnviarComandoLeia",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulcrumServiceServer).EnviarComandoLeia(ctx, req.(*ComandoSend))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulcrumService_InformarMerge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulcrumServiceServer).InformarMerge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FulcrumService/InformarMerge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulcrumServiceServer).InformarMerge(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulcrumService_InformarInicioEnvio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulcrumServiceServer).InformarInicioEnvio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FulcrumService/InformarInicioEnvio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulcrumServiceServer).InformarInicioEnvio(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulcrumService_EnviarComandoMerge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComandoSend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulcrumServiceServer).EnviarComandoMerge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FulcrumService/EnviarComandoMerge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulcrumServiceServer).EnviarComandoMerge(ctx, req.(*ComandoSend))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulcrumService_Mergan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulcrumServiceServer).Mergan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FulcrumService/Mergan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulcrumServiceServer).Mergan(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FulcrumService_EnviarComandoMergeFinal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComandoSend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FulcrumServiceServer).EnviarComandoMergeFinal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.FulcrumService/EnviarComandoMergeFinal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FulcrumServiceServer).EnviarComandoMergeFinal(ctx, req.(*ComandoSend))
	}
	return interceptor(ctx, in, info, handler)
}

// FulcrumService_ServiceDesc is the grpc.ServiceDesc for FulcrumService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FulcrumService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.FulcrumService",
	HandlerType: (*FulcrumServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnviarComando",
			Handler:    _FulcrumService_EnviarComando_Handler,
		},
		{
			MethodName: "EnviarComandoLeia",
			Handler:    _FulcrumService_EnviarComandoLeia_Handler,
		},
		{
			MethodName: "InformarMerge",
			Handler:    _FulcrumService_InformarMerge_Handler,
		},
		{
			MethodName: "InformarInicioEnvio",
			Handler:    _FulcrumService_InformarInicioEnvio_Handler,
		},
		{
			MethodName: "EnviarComandoMerge",
			Handler:    _FulcrumService_EnviarComandoMerge_Handler,
		},
		{
			MethodName: "Mergan",
			Handler:    _FulcrumService_Mergan_Handler,
		},
		{
			MethodName: "EnviarComandoMergeFinal",
			Handler:    _FulcrumService_EnviarComandoMergeFinal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/comunicacion.proto",
}
