broker: broker/broker.go
	go run broker/broker.go
fulcrum: fulcrum/fulcrum.go
	go run fulcrum/fulcrum.go
informante: informante/informante.go
	go run informante/informante.go
leia: leia/leia.go
	go run leia/leia.go
	
README: README.txt
	nano README.txt